server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  jta:
    enabled: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://10.90.1.220:3306/conditioncoupon_db?useSSL=false&allowMultiQueries=true
    username: conditioncoupon
    password: conditioncoupon!@34

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-aliases-package: com.project.cmn.mybatis.gen